version: '3.9'

networks:
  net:
    driver: bridge
services:
  server:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      # Default configuration for persist_directory in chromadb/config.py
      # Currently it's located in "/chroma/chroma/"
      # - chroma-data:/chroma/chroma/
      # changeme
      - chroma-data:/Users/eric/Data/chroma
    ports:
      - 8000:8000
    networks:
      - net

volumes:
  chroma-data:
    driver: local